import 'package:brain_pulse/core/Theming/text_style.dart';
import 'package:brain_pulse/features/more/ui/screen/my_profile.dart';
import 'package:brain_pulse/features/more/ui/screen/show_my_profile.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:path/path.dart';
import '../../core/Theming/colors.dart';
import '../../core/helpers/spacing.dart';

class More extends StatelessWidget {
  const More({super.key});
  static const String routeName = 'More';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: ColorsApp.white,
      body:
       Padding(
         padding: const EdgeInsets.only(top: 110 ,right: 10 , left: 10 ),
         child: SingleChildScrollView(
           child: Column(

             children: [
               const MyProfile(),
               gapH(10.h),
               buildSection(
                 title: "Personal Information",
                 items: [
                   buildListItem(context,Icons.person, "My profile", "....."),
                 ],
               ),
               buildSection(
                 title: "Settings",
                 items: [
                   buildListItem(context,Icons.language, "Language",
                       "Account language settings"),
                   buildListItem(context,Icons.mode_night_outlined, "Mode",
                       "Account Mode settings"),
                 ],
               ),
               buildSection(
                 title: "About Us",
                 items: [
                   buildListItem(context,Icons.mood_rounded, "About Us", "....."),
                 ],
               ),
             ],
           ),
         ),
       ),

    );
  }

  Widget buildSection({required String title, required List<Widget> items}) {
    return Padding(
      padding: EdgeInsets.all(16.w),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: TextStyleApp.font18boldBlack
          ),
          gapH(10.h),
          ...items,
        ],
      ),
    );
  }

  Widget buildListItem(BuildContext context,IconData icon, String title, String subtitle) {
    return Card(
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(15.r),
      ),
      child: ListTile(
        leading: Icon(icon, color: ColorsApp.blue),
        title: Text(
          title,
          style: TextStyleApp.font18boldBlack,
        ),
        subtitle: Text(subtitle),
        trailing: Icon(Icons.arrow_forward_ios, color: ColorsApp.grey),
        onTap: () {
          if (title == "My profile") {
            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => ShowMyProfile()),
            );
          }
          else if (title == "Language") {
            showBottomSheetOptions(context, "اختر اللغة", ["عربي", "English"]);
          }
          else if (title == "Mode") {
            showBottomSheetOptions(context, "اختر الوضع", ["نهاري", "ليلي"]);
          }
          else if (title == "About Us") {
            showBottomSheetOptions(context,"Electroencephalography (EEG) is a medical technique used to monitor and record electrical activity in the brain, helping doctors diagnose a variety of neurological disorders. Electrodes are placed on the scalp to pick up electrical signals generated by the activity of neurons. EEG is commonly used to diagnose epilepsy, sleep disorders, and changes in consciousness. Additionally, it can help evaluate conditions such as encephalitis, tumors, and brain injuries, making it a valuable tool in neurology",[]
            );
          }
        },
      ),
    );
  }
}
void showBottomSheetOptions(BuildContext context, String title, List<String> options) {
  showModalBottomSheet(
    context: context,
    shape: RoundedRectangleBorder(
      borderRadius: BorderRadius.vertical(top: Radius.circular(20.r)),
    ),
    builder: (BuildContext context) {
      return Container(
        padding: EdgeInsets.all(20.w),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(
              title,
              style: TextStyleApp.font18boldBlack,
            ),
            SizedBox(height: 20.h),
            ...options.map((option) => ListTile(
              title: Text(option),
              onTap: () {
                Navigator.pop(context);
              },
            )),
          ],
        ),
      );
    },
  );
}

